name: partylux
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 2.4.2+3

environment:
  sdk: '>=2.19.3 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  dio: ^5.3.3
  http: ^0.13.5
  path: ^1.8.2
  mime: ^1.0.4
  path_provider: ^2.1.1
  http_parser: ^4.0.2
  readmore:
  shared_preferences: ^2.0.20
  google_fonts: ^4.0.3
  country_picker: ^2.0.20
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.0
  flutter_spinkit: ^5.1.0
  pin_code_fields: ^8.0.1
  persistent_bottom_nav_bar:
  #intl: ^0.19.0
  shimmer: ^3.0.0
  clipboard: ^0.1.3
  intl_phone_number_input:
  percent_indicator: ^4.2.3
  image_picker: ^1.0.4
  #images_picker:
  #images_picker: ^1.2.11
  image_pickers: ^2.0.4+9
  flutter_slidable: ^3.0.0
  flutter_html: ^3.0.0-alpha.6
  flutter_easyloading: ^3.0.5
  syncfusion_flutter_datepicker: ^23.1.44
  flutter_keyboard_visibility: ^5.4.1
  flutter_polyline_points: ^1.0.0
  fluttertoast: ^8.2.2
  url_launcher: ^6.1.11
  photo_view: ^0.14.0
  google_places_flutter:
  smooth_page_indicator:
  currency_text_input_formatter: ^2.1.10
  webview_flutter: ^4.4.1
  google_maps_flutter: ^2.2.5
  geolocator: ^10.1.0
  geocoding: ^2.1.0
  permission_handler: ^11.0.1
  dotted_border:
  widget_to_marker:
  custom_info_window:
  flutter_custom_clippers:
  overlay_support:
  firebase_core: ^2.15.0
  firebase_database:
  firebase_messaging: ^14.6.5
  flutter_local_notifications: ^9.2.0
  flutter_background_geolocation:
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^5.0.0
  firebase_auth: ^4.7.2
  flutter_xlider: ^3.5.0
  flutter_dotenv: ^5.0.2
  simple_gradient_text: ^1.2.4
  flutter_svg:
  im_animations:
  infinite_scroll_pagination: ^4.0.0
  uuid: ^4.3.3
  pay: ^2.0.0
  flutter_stripe: ^10.1.1
  ai_barcode_scanner:
  qr_flutter: ^4.1.0
  uni_links: ^0.5.1
  chewie:
  video_player:
  flutter_timezone:
  flutter_image_compress:
  extended_image:
  image_cropper:


dev_dependencies:
  flutter_test:
    sdk: flutter

  # geofencing:
  #   path: ../FlutterGeofencing

  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.5


dependency_overrides:
  meta: ^1.10.0
  intl: ^0.19.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/applogo.png"
  min_sdk_android: 21
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

flutter_native_splash:
  #color: "#C5A866"
  background_image: assets/images/img_splash.png
  fullscreen: true
  android: true
  ios: true
  web: false


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/icon_assets/
    - assets/json/

  fonts:
    - family: Copperplate
      fonts:
        - asset: assets/fonts/copperplate/CopperplateCondensedSSiCondensed.ttf
          weight: 400
        - asset: assets/fonts/copperplate/OPTICopperplate-Heavy.otf
          weight: 500
        - asset: assets/fonts/copperplate/OPTICopperplate.otf
          weight: 700

    - family: Copperplate2
      fonts:
        - asset: assets/fonts/copperplate/OPTICopperplate.otf

    - family: Copperplate3
      fonts:
        - asset: assets/fonts/copperplate/Copperplate-Bold.ttf

    - family: lexenddeca
      fonts:
        - asset: assets/fonts/lexenddeca/LexendDeca-Light.ttf
          weight: 300
        - asset: assets/fonts/lexenddeca/LexendDeca-Medium.ttf
          weight: 400
        - asset: assets/fonts/lexenddeca/LexendDeca-Regular.ttf
          weight: 500
